"""user messages

Revision ID: 338803ce4cad
Revises: 06c8db51acc3
Create Date: 2020-06-20 12:50:14.089881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '338803ce4cad'
down_revision = '06c8db51acc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('recipient_id', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('sender_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'messages', 'users', ['sender_id'], ['id'])
    op.create_foreign_key(None, 'messages', 'users', ['recipient_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'sender_id')
    op.drop_column('messages', 'recipient_id')
    # ### end Alembic commands ###
