"""likedposts

Revision ID: 38612c28e576
Revises: b5b3f8a4764f
Create Date: 2020-06-20 11:49:26.905866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38612c28e576'
down_revision = 'b5b3f8a4764f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postLikes',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('postLikes')
    # ### end Alembic commands ###
