"""empty message

Revision ID: 4196b6659b67
Revises: 57963089dbf1
Create Date: 2020-07-04 16:56:57.832946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4196b6659b67'
down_revision = '57963089dbf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_picture')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_picture', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
