"""image cv_tags

Revision ID: 4da4046bb736
Revises: 7e148499fc0f
Create Date: 2021-01-03 15:09:20.268403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4da4046bb736'
down_revision = '7e148499fc0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('cv_tags', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'cv_tags')
    # ### end Alembic commands ###
