"""update profile_picture

Revision ID: 57963089dbf1
Revises: df68046dd88e
Create Date: 2020-07-04 16:37:31.062146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57963089dbf1'
down_revision = 'df68046dd88e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'isAdmin',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'isMember',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'isWriter',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'isWriter',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'isMember',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'isAdmin',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
