"""user isPublic

Revision ID: 7e148499fc0f
Revises: d8dfe0396763
Create Date: 2021-01-03 15:07:10.242808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e148499fc0f'
down_revision = 'd8dfe0396763'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('isPublic', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'isPublic')
    # ### end Alembic commands ###
