"""comments

Revision ID: 970151f73a9f
Revises: dafab4040f75
Create Date: 2020-06-20 10:38:41.525645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '970151f73a9f'
down_revision = 'dafab4040f75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datePosted', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    # ### end Alembic commands ###
