"""user last login

Revision ID: a7b612b628fe
Revises: cb678812973b
Create Date: 2020-07-21 13:19:34.643767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7b612b628fe'
down_revision = 'cb678812973b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('lastLoggedIn', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'lastLoggedIn')
    # ### end Alembic commands ###
