"""comment datetime

Revision ID: ae318a4821e4
Revises: 970151f73a9f
Create Date: 2020-06-20 11:08:05.551287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae318a4821e4'
down_revision = '970151f73a9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'timestamp')
    # ### end Alembic commands ###
