"""caption, alt_tag images

Revision ID: b1eb491021fe
Revises: a7b612b628fe
Create Date: 2020-07-21 17:07:56.263585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1eb491021fe'
down_revision = 'a7b612b628fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('alt_tag', sa.String(), nullable=True))
    op.add_column('images', sa.Column('caption', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'caption')
    op.drop_column('images', 'alt_tag')
    # ### end Alembic commands ###
