"""intro isEditor

Revision ID: cb678812973b
Revises: b1bad181e80e
Create Date: 2020-07-21 13:18:53.820378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb678812973b'
down_revision = 'b1bad181e80e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('intro', sa.String(), nullable=True))
    op.add_column('users', sa.Column('isEditor', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'isEditor')
    op.drop_column('posts', 'intro')
    # ### end Alembic commands ###
