"""image upload and public

Revision ID: d8dfe0396763
Revises: aa385809c318
Create Date: 2020-12-19 16:31:46.626747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8dfe0396763'
down_revision = 'aa385809c318'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.add_column('images', sa.Column('uploaded_datetime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'uploaded_datetime')
    op.drop_column('images', 'is_public')
    # ### end Alembic commands ###
