"""admin/writer/member

Revision ID: dafab4040f75
Revises: f4ff4ac2d0bb
Create Date: 2020-06-20 09:50:17.426038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dafab4040f75'
down_revision = 'f4ff4ac2d0bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('isAdmin', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('isMember', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('isWriter', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'isWriter')
    op.drop_column('users', 'isMember')
    op.drop_column('users', 'isAdmin')
    # ### end Alembic commands ###
