"""comment message

Revision ID: e852aae697df
Revises: ae318a4821e4
Create Date: 2020-06-20 11:26:59.503511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e852aae697df'
down_revision = 'ae318a4821e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'message')
    # ### end Alembic commands ###
