"""post images

Revision ID: fe2760a3bd76
Revises: b7be8f52faec
Create Date: 2020-07-05 15:17:59.678309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe2760a3bd76'
down_revision = 'b7be8f52faec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postImages',
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], )
    )
    op.add_column('posts', sa.Column('heroImage_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'images', ['heroImage_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'heroImage_id')
    op.drop_table('postImages')
    # ### end Alembic commands ###
